




FROM ubuntu:18.04
RUN apt-get update && apt-get install python3-pip -y && pip3 install flask==2.0.0
ADD server.py /my_server/server.py
WORKDIR /my_server/
EXPOSE 5000
CMD python3 server.py

# worddir does not copy anything but just sets the dir
# COPY / ADD "bakes" the files into the image
# VOLUME allow data to live outside the container
