# to run in background:
#        docker-compose -f docker-compose-elastic.yml up -d
# to execute inside shell:
#                          docker exec -it my_es_container /bin/bash
# check status:
#              docker-compose ps

# test:
#       curl http://localhost:9200/_cluster/health


# shut down and remove:
#           docker-compose -f docker-compose-elastic.yml down


# only stop:
#          docker-compose -f docker-compose-elastic.yml stop


# to inspect:
#            docker container inspect my_es_container





services:
  elasticsearch:
    image: elasticsearch:7.2.0
    container_name: my_es_container
    environment:
      - discovery.type=single-node
      - my_variable=hello everyone  
    ports:
      - "9200:9200" # curl -X GET -i http://localhost:9200
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:9200/_cluster/health"]
      interval: 5s
      timeout: 3s
      retries: 10