services:
  api:
    image: datascientest/fastapi:1.0.0
    container_name: api
    ports:
      - "8000:8000"
    networks:
      - test-network
  auth-test:
    build:
      context: .
      args:
        TEST_FILE: auth_test.py
    volumes:
      - log-volume:/app/logs
      - ./requirements.txt:/app/requirements.txt
    environment:
      - LOG=1
    depends_on:
      - api
    networks:
      - test-network
    command: ["python", "test.py"]
  authz-test:
    build:
      context: .
      args:
        TEST_FILE: authz_test.py
    volumes:
      - log-volume:/app/logs
      - ./requirements.txt:/app/requirements.txt
    environment:
      - LOG=1
    depends_on:
      - api
    networks:
      - test-network
    command: ["python", "test.py"]
  content-test:
    build:
      context: .
      args:
        TEST_FILE: content_test.py
    volumes:
      - log-volume:/app/logs
      - ./requirements.txt:/app/requirements.txt
    environment:
      - LOG=1
    depends_on:
      - api
    networks:
      - test-network
    command: ["python", "test.py"]
networks:
  test-network:
    driver: bridge
volumes:
  log-volume: